management:
 endpoints:
  web:
    exposure:
      include: '*'
 endpoint:
  health:
    show-details: always
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/school_system_jpa
    #username: appUser
    #password: appuser
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
  application:
    name: school-system
  boot:
    admin:
      client:
        url: http://localhost:9001    